// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePIN(arg1, arg2) {
  return window['go']['main']['App']['ChangePIN'](arg1, arg2);
}

export function GetAPIKeyMasked() {
  return window['go']['main']['App']['GetAPIKeyMasked']();
}

export function GetAvailableStrategies() {
  return window['go']['main']['App']['GetAvailableStrategies']();
}

export function GetBotStatus() {
  return window['go']['main']['App']['GetBotStatus']();
}

export function GetCurrentPosition() {
  return window['go']['main']['App']['GetCurrentPosition']();
}

export function GetDefaultStrategyParams(arg1) {
  return window['go']['main']['App']['GetDefaultStrategyParams'](arg1);
}

export function GetEnvFilePath() {
  return window['go']['main']['App']['GetEnvFilePath']();
}

export function GetSetupInstructions() {
  return window['go']['main']['App']['GetSetupInstructions']();
}

export function GetTradeHistory(arg1) {
  return window['go']['main']['App']['GetTradeHistory'](arg1);
}

export function GetTradeSummary() {
  return window['go']['main']['App']['GetTradeSummary']();
}

export function GetTradesByDateRange(arg1, arg2) {
  return window['go']['main']['App']['GetTradesByDateRange'](arg1, arg2);
}

export function GetWalletBalance() {
  return window['go']['main']['App']['GetWalletBalance']();
}

export function HasPIN() {
  return window['go']['main']['App']['HasPIN']();
}

export function IsLocked() {
  return window['go']['main']['App']['IsLocked']();
}

export function IsSetupComplete() {
  return window['go']['main']['App']['IsSetupComplete']();
}

export function LockApp() {
  return window['go']['main']['App']['LockApp']();
}

export function RemovePIN() {
  return window['go']['main']['App']['RemovePIN']();
}

export function SaveAPIKeys(arg1, arg2) {
  return window['go']['main']['App']['SaveAPIKeys'](arg1, arg2);
}

export function SetPIN(arg1) {
  return window['go']['main']['App']['SetPIN'](arg1);
}

export function StartBot(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartBot'](arg1, arg2, arg3, arg4, arg5);
}

export function StopBot() {
  return window['go']['main']['App']['StopBot']();
}

export function UnlockApp(arg1) {
  return window['go']['main']['App']['UnlockApp'](arg1);
}

export function UpdateAPIKeys(arg1, arg2) {
  return window['go']['main']['App']['UpdateAPIKeys'](arg1, arg2);
}

export function ValidateConfig(arg1, arg2) {
  return window['go']['main']['App']['ValidateConfig'](arg1, arg2);
}
