// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {database} from '../models';

export function ChangePIN(arg1:string,arg2:string):Promise<void>;

export function GetAPIKeyMasked():Promise<string>;

export function GetAvailableStrategies():Promise<Array<main.StrategyInfo>>;

export function GetBotStatus():Promise<main.BotStatus>;

export function GetCurrentPosition():Promise<database.Position>;

export function GetDefaultStrategyParams(arg1:string):Promise<Record<string, any>>;

export function GetEnvFilePath():Promise<string>;

export function GetMultiTimeframeData():Promise<Record<string, main.TimeframeChartData>>;

export function GetSetupInstructions():Promise<string>;

export function GetTimeframeData(arg1:string):Promise<main.TimeframeChartData>;

export function GetTradeHistory(arg1:number):Promise<Array<database.Trade>>;

export function GetTradeSummary():Promise<database.TradeSummary>;

export function GetTradesByDateRange(arg1:string,arg2:string):Promise<Array<database.Trade>>;

export function GetWalletBalance():Promise<Array<main.WalletBalance>>;

export function HasPIN():Promise<boolean>;

export function IsLocked():Promise<boolean>;

export function IsSetupComplete():Promise<boolean>;

export function LockApp():Promise<void>;

export function RemovePIN():Promise<void>;

export function ResetSetup():Promise<void>;

export function SaveAPIKeys(arg1:string,arg2:string):Promise<void>;

export function SetPIN(arg1:string):Promise<void>;

export function StartBot(arg1:string,arg2:string,arg3:number,arg4:boolean,arg5:Record<string, any>):Promise<void>;

export function StopBot():Promise<void>;

export function UnlockApp(arg1:string):Promise<void>;

export function UpdateAPIKeys(arg1:string,arg2:string):Promise<void>;

export function ValidateConfig(arg1:string,arg2:Record<string, any>):Promise<void>;
