package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// SetupManager handles first-time setup configuration
type SetupManager struct {
	configDir     string
	envFilePath   string
	setupComplete bool
	apiEndpoint   string // Binance API endpoint
}

// NewSetupManager creates a new setup manager
func NewSetupManager() *SetupManager {
	// Get user config directory
	configDir, err := os.UserConfigDir()
	if err != nil {
		configDir = "."
	}

	appConfigDir := filepath.Join(configDir, "trading-bot")
	envPath := filepath.Join(appConfigDir, ".env")

	return &SetupManager{
		configDir:   appConfigDir,
		envFilePath: envPath,
		apiEndpoint: "https://api.binance.us", // Default to Binance US (US users)
	}
}

// Initialize checks if setup is complete
func (s *SetupManager) Initialize() error {
	// Check if .env file exists
	if _, err := os.Stat(s.envFilePath); err == nil {
		// File exists, check if it has API keys
		data, err := os.ReadFile(s.envFilePath)
		if err != nil {
			return fmt.Errorf("failed to read .env file: %w", err)
		}

		content := string(data)
		hasAPIKey := strings.Contains(content, "BINANCE_API_KEY=") &&
			!strings.Contains(content, "BINANCE_API_KEY=your_key_here")
		hasAPISecret := strings.Contains(content, "BINANCE_API_SECRET=") &&
			!strings.Contains(content, "BINANCE_API_SECRET=your_secret_here")

		// Load API endpoint from .env if present
		lines := strings.Split(content, "\n")
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, "BINANCE_API_ENDPOINT=") {
				s.apiEndpoint = strings.TrimPrefix(line, "BINANCE_API_ENDPOINT=")
			}
		}

		s.setupComplete = hasAPIKey && hasAPISecret
	} else {
		s.setupComplete = false
	}

	return nil
}

// IsSetupComplete returns whether initial setup is done
func (s *SetupManager) IsSetupComplete() bool {
	return s.setupComplete
}

// SaveAPIKeys saves user's Binance API keys
func (s *SetupManager) SaveAPIKeys(apiKey, apiSecret string) error {
	if apiKey == "" || apiSecret == "" {
		return fmt.Errorf("API key and secret cannot be empty")
	}

	// Validate API key format (basic check)
	if len(apiKey) < 20 {
		return fmt.Errorf("API key appears invalid (too short)")
	}
	if len(apiSecret) < 20 {
		return fmt.Errorf("API secret appears invalid (too short)")
	}

	// Create config directory if it doesn't exist
	if err := os.MkdirAll(s.configDir, 0700); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Create .env file content with API endpoint
	envContent := fmt.Sprintf(`# Binance API Configuration
# Generated by Trading Bot Setup Wizard
# Keep this file secure and never share it

BINANCE_API_KEY=%s
BINANCE_API_SECRET=%s
BINANCE_API_ENDPOINT=%s

# API Configuration Notes:
# - These keys are used to connect to Binance for trading
# - Ensure "Enable Trading" is ON in Binance API settings
# - Ensure "Enable Withdrawals" is OFF for security
# - Consider restricting API to your IP address
#
# API Endpoint Options:
# - https://api.binance.com (Regular Binance - Global)
# - https://api.binance.us (Binance US)
# - https://testnet.binance.vision (Testnet - for testing)
`, apiKey, apiSecret, s.apiEndpoint)

	// Write to file with secure permissions (0600 = owner read/write only)
	if err := os.WriteFile(s.envFilePath, []byte(envContent), 0600); err != nil {
		return fmt.Errorf("failed to save .env file: %w", err)
	}

	// Set environment variables for current session
	os.Setenv("BINANCE_API_KEY", apiKey)
	os.Setenv("BINANCE_API_SECRET", apiSecret)

	s.setupComplete = true
	return nil
}

// GetEnvFilePath returns the path to the .env file
func (s *SetupManager) GetEnvFilePath() string {
	return s.envFilePath
}

// LoadAPIKeys loads existing API keys (for verification)
func (s *SetupManager) LoadAPIKeys() (apiKey, apiSecret string, err error) {
	data, err := os.ReadFile(s.envFilePath)
	if err != nil {
		return "", "", fmt.Errorf("failed to read .env file: %w", err)
	}

	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "BINANCE_API_KEY=") {
			apiKey = strings.TrimPrefix(line, "BINANCE_API_KEY=")
		} else if strings.HasPrefix(line, "BINANCE_API_SECRET=") {
			apiSecret = strings.TrimPrefix(line, "BINANCE_API_SECRET=")
		}
	}

	if apiKey == "" || apiSecret == "" {
		return "", "", fmt.Errorf("API keys not found in .env file")
	}

	return apiKey, apiSecret, nil
}

// GetMaskedAPIKey returns API key with most characters hidden
func (s *SetupManager) GetMaskedAPIKey() (string, error) {
	apiKey, _, err := s.LoadAPIKeys()
	if err != nil {
		return "", err
	}

	if len(apiKey) < 8 {
		return "****", nil
	}

	// Show first 4 and last 4 characters
	return apiKey[:4] + strings.Repeat("*", len(apiKey)-8) + apiKey[len(apiKey)-4:], nil
}

// ValidateAPIKeys performs basic validation
func (s *SetupManager) ValidateAPIKeys(apiKey, apiSecret string) error {
	if apiKey == "" {
		return fmt.Errorf("API key is required")
	}
	if apiSecret == "" {
		return fmt.Errorf("API secret is required")
	}
	if len(apiKey) < 20 {
		return fmt.Errorf("API key appears too short (minimum 20 characters)")
	}
	if len(apiSecret) < 20 {
		return fmt.Errorf("API secret appears too short (minimum 20 characters)")
	}
	if strings.Contains(apiKey, " ") {
		return fmt.Errorf("API key should not contain spaces")
	}
	if strings.Contains(apiSecret, " ") {
		return fmt.Errorf("API secret should not contain spaces")
	}
	if apiKey == "your_key_here" || apiSecret == "your_secret_here" {
		return fmt.Errorf("please enter your actual API keys from Binance")
	}

	return nil
}

// UpdateAPIKeys updates existing API keys
func (s *SetupManager) UpdateAPIKeys(apiKey, apiSecret string) error {
	// Same as SaveAPIKeys, but for updating
	return s.SaveAPIKeys(apiKey, apiSecret)
}

// ResetSetup clears all saved credentials and resets setup state
func (s *SetupManager) ResetSetup() error {
	// Delete .env file if it exists
	if err := os.Remove(s.envFilePath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to delete .env file: %w", err)
	}

	// Clear environment variables
	os.Unsetenv("BINANCE_API_KEY")
	os.Unsetenv("BINANCE_API_SECRET")

	// Mark setup as incomplete
	s.setupComplete = false

	return nil
}

// GetAPIEndpoint returns the configured API endpoint
func (s *SetupManager) GetAPIEndpoint() string {
	if s.apiEndpoint == "" {
		return "https://api.binance.us" // Default to Binance US
	}
	return s.apiEndpoint
}

// SetAPIEndpoint sets the API endpoint to use
func (s *SetupManager) SetAPIEndpoint(endpoint string) {
	s.apiEndpoint = endpoint
}

// GetSetupInstructions returns help text for users
func (s *SetupManager) GetSetupInstructions() string {
	return `How to Get Your Binance API Keys:

1. Log in to Binance (https://www.binance.com)
2. Go to Profile → API Management
3. Click "Create API"
4. Name it "Trading Bot" or similar
5. Complete 2FA verification
6. Copy your API Key and Secret Key

IMPORTANT Security Settings:
- Enable "Enable Trading" ✓
- DISABLE "Enable Withdrawals" ✗ (for security!)
- Consider restricting to your IP address
- Never share your API keys with anyone

For Testing:
- Use Binance Testnet: https://testnet.binance.vision
- Create testnet API keys (no real money)
- Test the bot thoroughly before using real funds
`
}
